platform :ios, '15.5'
use_frameworks!

target 'Runner' do
    pod 'GoogleMLKit/TextRecognition', '8.0.0'
    pod 'GoogleMLKit/TextRecognitionChinese', '8.0.0'
    pod 'GoogleMLKit/TextRecognitionDevanagari', '8.0.0'
    pod 'GoogleMLKit/TextRecognitionJapanese', '8.0.0'
    pod 'GoogleMLKit/TextRecognitionKorean', '8.0.0'
end
